from django.db import models

class Countries(models.Model): # primary_key done
    id_country = models.CharField(primary_key = True)
    country_name = models.CharField()

class Competitions(models.Model): # primary_key done
    id_country = models.ForeignKey(Countries) ## Add model  
    id_competition = models.CharField(primary_key=True)
    competition_flashscore = models.CharField()
    competition_sofifa = models.CharField()
    is_cup = models.BooleanField()

class TeamsFlashscore(models.Model): # primary_key done!
    id_team = models.CharField(primary_key=True)
    team_name = models.CharField()
    url_team = models.URLField()

class TeamsSofifa(models.Model): # primary_key done
    id_team_sofifa = models.CharField(primary_key = True)
    team_name = models.CharField()
    home_stadium = models.CharField()
    international_prestige = models.IntegerField()
    domestic_prestige = models.IntegerField()
    id_rival_team_sofifa = models.CharField() # TODO: add unique param
    rival_team_name = models.CharField()
    url_team = models.URLField()
    id_country = models.ForeignKey(Countries)

class CoachesFlashscore(models.Model): # primary_key done!
    id_coach = models.CharField(primary_key=True)
    coach_name = models.CharField()
    url_coach = models.URLField()

class PlayersFlashscore(models.Model): # primary_key done!
    id_player = models.CharField(primary_key = True)
    player_name = models.CharField()
    player_url  = models.URLField()

class PlayersSofifa(models.Model): # primary_key done!
    id_player_sofifa = models.CharField(primary_key = True)
    player_name = models.CharField()
    height = models.IntegerField()
    preferred_foot = models.CharField()
    url_player = models.URLField()

class PlayersFifa(models.Model): # primary_key done!
    id_player_sofifa = models.ForeignKey(PlayersSofifa)
    age = models.IntegerField()
    overall_rating =  models.IntegerField()
    potential =  models.IntegerField()
    value = models.CharField()
    wage = models.CharField()
    id_team_sofifa = models.ForeignKey(TeamsSofifa) 
    fifa = models.CharField()
    date = models.DateTimeField()
    id_country = models.ForeignKey(Countries) 
    id_competition = models.ForeignKey(Competitions) 

class Matches(models.Model):
    id_match = models.CharField(primary_key = True)
    date = models.DateTimeField()
    referee = models.CharField()
    venue = models.TextField()
    capacity = models.IntegerField()
    attendance = models.IntegerField()
    goals_home = models.IntegerField()
    goals_away = models.IntegerField()
    id_team_home = models.ForeignKey(TeamsFlashscore) 
    id_team_away = models.ForeignKey(TeamsFlashscore) 
    expected_goals_xg_home = models.DecimalField(max_digits=4, decimal_places=2)
    expected_goals_xg_away = models.DecimalField(max_digits=4, decimal_places=2)
    ball_possession_home = models.CharField(max_lenght=3)
    ball_possession_away = models.CharField(max_lenght=3)
    goal_attempts_home = models.IntegerField()
    goal_attempts_away = models.IntegerField()
    shots_on_goal_home = models.IntegerField()
    shots_on_goal_away = models.IntegerField()
    shots_off_goal_home = models.IntegerField()
    shots_off_goal_away = models.IntegerField()
    free_kicks_home = models.IntegerField()
    free_kicks_away = models.IntegerField()
    corner_kicks_home = models.IntegerField()
    corner_kicks_away = models.IntegerField()
    offsides_home = models.IntegerField()
    offsides_away = models.IntegerField()
    throw_ins_home = models.IntegerField()
    throw_ins_away = models.IntegerField()
    goalkeeper_saves_home = models.IntegerField()
    goalkeeper_saves_away = models.IntegerField()
    fouls_home = models.IntegerField()
    fouls_away = models.IntegerField()
    yellow_cards_home = models.IntegerField()
    yellow_cards_away = models.IntegerField()
    total_passes_home = models.IntegerField()
    total_passes_away = models.IntegerField()
    tackles_home = models.IntegerField()
    tackles_away = models.IntegerField()
    attacks_home = models.IntegerField()
    attacks_away = models.IntegerField()
    dangerous_attacks_home = models.IntegerField()
    dangerous_attacks_away = models.IntegerField()
    clearances_completed_home = models.IntegerField()
    clearances_completed_away = models.IntegerField()
    id_coach_home = models.ForeignKey(CoachesFlashscore)
    id_coach_away = models.ForeignKey(CoachesFlashscore)
    id_country = models.ForeignKey(Countries)
    id_competition = models.ForeignKey(Competitions)
    is_cup = models.BooleanField()
    season = models.CharField(max_lenght=9)
    red_cards_home = models.IntegerField()
    red_cards_away = models.IntegerField()
    blocked_shots_home = models.IntegerField()
    blocked_shots_away = models.IntegerField()
    completed_passes_home = models.IntegerField()
    completed_passes_away = models.IntegerField()
    pass_success_home = models.CharField()
    pass_success_away = models.CharField()
    goal_kicks_home = models.IntegerField()
    goal_kicks_away = models.IntegerField()

class FormationFlashscore(models.Model): # primary_key done!
   
    id_match = models.OneToOneField(Matches, primary_key=True)

    id_player_start_home_1 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_home_2 = models.ForeignKey(PlayersFlashscore)  
    id_player_start_home_3 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_home_4 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_home_5 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_home_6 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_home_7 = models.ForeignKey(PlayersFlashscore)
    id_player_start_home_8 = models.ForeignKey(PlayersFlashscore)   
    id_player_start_home_9 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_home_10 = models.ForeignKey(PlayersFlashscore)   
    id_player_start_home_11 = models.ForeignKey(PlayersFlashscore) 

    id_player_start_away_1 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_away_2 = models.ForeignKey(PlayersFlashscore) 
    id_player_start_away_3 = models.ForeignKey(PlayersFlashscore)  
    id_player_start_away_4 = models.ForeignKey(PlayersFlashscore)  
    id_player_start_away_5 = models.ForeignKey(PlayersFlashscore)   
    id_player_start_away_6 = models.ForeignKey(PlayersFlashscore)  
    id_player_start_away_7 = models.ForeignKey(PlayersFlashscore)   
    id_player_start_away_8 = models.ForeignKey(PlayersFlashscore)   
    id_player_start_away_9 = models.ForeignKey(PlayersFlashscore)  
    id_player_start_away_10 = models.ForeignKey(PlayersFlashscore)    
    id_player_start_away_11 = models.ForeignKey(PlayersFlashscore)    

    id_player_sub_home_1 = models.ForeignKey(PlayersFlashscore)  
    id_player_sub_home_2 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_home_3 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_home_4 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_home_5 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_home_6 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_home_7 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_home_8 = models.ForeignKey(PlayersFlashscore)  
    id_player_sub_home_9 = models.ForeignKey(PlayersFlashscore) 

    id_player_sub_away_1 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_away_2 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_away_3 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_away_4 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_away_5 = models.ForeignKey(PlayersFlashscore)  
    id_player_sub_away_6 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_away_7 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_away_8 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_away_9 = models.ForeignKey(PlayersFlashscore)

    id_player_sub_enter_home_1 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_enter_home_2 = models.ForeignKey(PlayersFlashscore)  
    id_player_sub_enter_home_3 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_enter_home_4 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_enter_home_5 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_enter_home_6 = models.ForeignKey(PlayersFlashscore) 

    id_player_sub_enter_away_1 = models.ForeignKey(PlayersFlashscore)  
    id_player_sub_enter_away_2 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_enter_away_3 = models.ForeignKey(PlayersFlashscore)
    id_player_sub_enter_away_4 = models.ForeignKey(PlayersFlashscore) 
    id_player_sub_enter_away_5 = models.ForeignKey(PlayersFlashscore)  
    id_player_sub_enter_away_6 = models.ForeignKey(PlayersFlashscore) 

    id_player_miss_home_1 = models.ForeignKey(PlayersFlashscore) 
    id_player_miss_home_2 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_home_3 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_home_4 = models.ForeignKey(PlayersFlashscore)    
    id_player_miss_home_5 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_home_6 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_home_7 = models.ForeignKey(PlayersFlashscore)  
    id_player_miss_home_8 = models.ForeignKey(PlayersFlashscore) 
    id_player_miss_home_9 = models.ForeignKey(PlayersFlashscore) 
    id_player_miss_home_10 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_home_11 = models.ForeignKey(PlayersFlashscore) 
    id_player_miss_home_12 = models.ForeignKey(PlayersFlashscore)

    id_player_miss_away_1 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_away_2 = models.ForeignKey(PlayersFlashscore) 
    id_player_miss_away_3 = models.ForeignKey(PlayersFlashscore) 
    id_player_miss_away_4 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_away_5 = models.ForeignKey(PlayersFlashscore)  
    id_player_miss_away_6 = models.ForeignKey(PlayersFlashscore) 
    id_player_miss_away_7 = models.ForeignKey(PlayersFlashscore)
    id_player_miss_away_8 = models.ForeignKey(PlayersFlashscore)  
    id_player_miss_away_9 = models.ForeignKey(PlayersFlashscore)   
    id_player_miss_away_10 = models.ForeignKey(PlayersFlashscore)   
    id_player_miss_away_11 = models.ForeignKey(PlayersFlashscore)  
    id_player_miss_away_12 = models.ForeignKey(PlayersFlashscore) 

class Odds(models.Model): # primary_key done!
    id_match = models.OneToOneField(Matches, on_delete=models.CASCADE, primary_key=True) # Cascade, set_null, set_default, protect
    odds_home = models.DecimalField(max_digits=5, decimal_places=2)
    odds_draw = models.DecimalField(max_digits=5, decimal_places=2)
    odds_away = models.DecimalField(max_digits=5, decimal_places=2)