# Generated by Django 5.0.2 on 2024-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_added_time_col"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="app/images")),
            ],
        ),
    ]
