# Generated by Django 5.0.2 on 2024-03-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_over_predictions_overround_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictions",
            old_name="id_predic",
            new_name="id_match",
        ),
        migrations.AlterField(
            model_name="predictions",
            name="overround",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="predictions",
            name="predicted_result",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="predictions",
            name="stake_mod",
            field=models.IntegerField(),
        ),
    ]
