# Generated by Django 5.0.2 on 2024-03-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_id_match_and_changes_in_data_types"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoachesFlashscore",
            new_name="CoachFlashscore",
        ),
        migrations.RenameModel(
            old_name="Competitions",
            new_name="Competition",
        ),
        migrations.RenameModel(
            old_name="Countries",
            new_name="Country",
        ),
        migrations.RenameModel(
            old_name="Matches",
            new_name="Match",
        ),
        migrations.RenameModel(
            old_name="Odds",
            new_name="Odd",
        ),
        migrations.RenameModel(
            old_name="PlayersFifa",
            new_name="PlayerFifa",
        ),
        migrations.RenameModel(
            old_name="PlayersFlashscore",
            new_name="PlayerFlashscore",
        ),
        migrations.RenameModel(
            old_name="PlayersSofifa",
            new_name="PlayerSofifa",
        ),
        migrations.RenameModel(
            old_name="Predictions",
            new_name="Prediction",
        ),
        migrations.RenameModel(
            old_name="TeamsFlashscore",
            new_name="TeamFlashscore",
        ),
        migrations.RenameModel(
            old_name="TeamsSofifa",
            new_name="TeamSofifa",
        ),
        migrations.AlterModelOptions(
            name="prediction",
            options={"ordering": ["id_team_home"]},
        ),
    ]
