# Generated by Django 5.0.2 on 2024-03-31 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_all_classes_to_singular"),
    ]

    operations = [
        migrations.AddField(
            model_name="prediction",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="prediction",
            name="date",
            field=models.DateField(),
        ),
    ]
