name: Create action update_predictions.yml in schedule

on:
  schedule:
    - cron: "0 3 * * MON"  # Ejecutar Lunes a la madrugada (luego de get_predictios.yml)

jobs:

  update-workflow:

    runs-on: ubuntu-latest

    steps:

    # Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          automatize_predict
        sparse-checkout-cone-mode: false
        ref: prod  # Branch

    # Instalo dependencias
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pandas openpyxl

    # Ejecuto create_action_update.py
    - name: Create cronjob in next matches's schedule.
      run: python automatize_predict/update_predictions/create_action_update.py
