name: Create action update_predictions.yml in schedule

on:
  push: # Prueba
    branches:
      - staging
  schedule:
    - cron: "0 3 * * MON"  # Ejecutar Lunes a la madrugada (luego de get_predictios.yml)

jobs:

  update-workflow:

    runs-on: ubuntu-latest
    
    # Agrego permisos al job para poder hacer push
    permissions: 
      contents: write # Permiso para pushear cambios a repo de Github 

    steps:

    # Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          automatize_predict
          p6_deployment
        sparse-checkout-cone-mode: false
        ref: prod  # Branch

    # Instalo dependencias
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pandas openpyxl requests

    - name: Check token scopes
      run: "curl -I -H \"Authorization: token ${{ secrets.TOKEN }}\" https://api.github.com/nachomondino1/predictor-apuestas"

    # Ejecuto create_action_update.py
    - name: Create cronjob in next matches's schedule.
      run: python automatize_predict/update_predictions/create_action_update.py --token ${{ secrets.TOKEN }}

    # Git push (para actualizar update_predictions.yml)
    - name: Commit and push all changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .  # Agregar todos los cambios
        git commit -m "Create update_predictions.yml"
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:prod
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }} # Set the environment variable GITHUB_TOKEN if needed for push authentication
