name: Create Update action

on:
  schedule:
    - cron: "0 0 * * FRI"  # Ejecutar Viernes a la medianoche

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          automatize_predict
        sparse-checkout-cone-mode: false
        ref: prod  # Branch

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pandas openpyxl

    - name: Run update script
      run: python automatize_predict/update_predictions/create_action_update_predictions.py
