name: Update Workflow

on:
  schedule:
    - cron: '0 0 */3 * *'  # Ejecutar cada 3 días a la medianoche
  push:
    paths:
      - 'github_actions/update_workflow/schedules.xlsx'

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          github_actions/update_workflow/schedules.xlsx
          github_actions/update_workflow/update_workflow.py
        sparse-checkout-cone-mode: false
        ref: prod  # Branch

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pandas openpyxl

    - name: Run update script
      run: python p6_deployment/update_workflow.py
