name: Get predictions next 15 days

on:
  # push: # Para actualizar predicciones de USA por tener nuevo modelo
  #   branches:
  #     - staging
  #     - prod
  schedule:
    - cron: "0 0 * * FRI"  # Ejecutar Lunes a la medianoche

jobs:
  collect_predictions:
    runs-on: ubuntu-latest

    env:
      TZ: America/Argentina/Buenos_Aires
      ENVIRONMENT: "prod"

    # Agrego permisos en job para poder hacer push
    permissions: 
      contents: write  # para poder hacer git push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: prod  # Branch

      - name: Print current date and time
        run: date
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
 
      - name: Set up cache for pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_mnm.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements_mnm.txt

      - name: Run collect_predictions script
        run: |
          # python automatize_predict/collect_predictions.py 15 "[48, 55, 59, 77, 148, 167]" '{"run_missing": true, "data_unders": true, "data_prep": true, "modeling": true, "export": true}'
          python automatize_predict/collect_predictions.py 15 "[167]" '{"run_missing": true, "data_unders": true, "data_prep": true, "modeling": true, "export": true}' # De prueba

      - name: Commit and push all changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Set the environment variable GITHUB_TOKEN if needed for push authentication
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .  # Agregar todos los cambios
          git commit -m "Get predictions next 15 days"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:prod

      - name: Dispatch event to second repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python automatize_predict/dispatch_event/dispatch_event.py
