name: Get predictions next 15 days

on:
  push
  # schedule:
  #   - cron: "0 0 */2 * *"  # Ejecutar cada 2 días a la medianoche

jobs:
  collect_predictions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # sparse-checkout: |
          #   venv_mnm
          #   requirements_mnm.txt
          #   github_actions/automatize_predict
          #   p6_deployment/collect_data.py
          #   p6_deployment/main_next_matches.py  # Asegúrate de incluir este archivo si es necesario
          #   p6_deployment/data/predicciones.xlsx
          # sparse-checkout-cone-mode: false
          ref: ignacio/deployment/automatize_predict  # Branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
 
      - name: Install dependencies
        run: |
          pip install -r requirements_mnm.txt

      - name: Run collect_predictions script
        run: |
          python github_actions/automatize_predict/collect_predictions.py 15 "[48, 55, 59, 77, 167]"

      - name: Commit and push predictions.xlsx
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add p6_deployment/data/predicciones.xlsx
          git commit -m "Add predicciones.xlsx of next 15 days"
          git push
        env:
          # Set the environment variable GITHUB_TOKEN if needed for push authentication
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
