name: Get predictions next 15 days

on:
  schedule:
    - cron: "*/2 * * * *"  # Prueba
    - cron: "0 0 */7 * *"  # Ejecutar cada 2 días a la medianoche 
  push:
    branches:
      - prod

jobs:
  collect_predictions:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/prod'  # Asegura que el job se ejecute solo en la rama prod

    # Agrego permisos para poder hacer push
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: prod  # Branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
 
      - name: Set up cache for pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_mnm.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements_mnm.txt

      - name: Run collect_predictions script
        run: |
          python automatize_predict/collect_predictions.py 1.5 "[167]"  # [48, 55, 59, 77, 167]

      - name: Commit and push predictions.xlsx
        env:
          # Set the environment variable GITHUB_TOKEN if needed for push authentication
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add p6_deployment/data/predicciones.xlsx
          git commit -m "Add predicciones.xlsx of next 15 days"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:prod

      - name: Dispatch event to second repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python automatize_predict/dispatch_event/dispatch_event.py
