name: Transfer Excel Files

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test SSH Connection
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{ secrets.SSH_password }}
        port: 22
        script: |
          echo "SSH connection successful"
