name: Run predictions

on:
  schedule:
    - cron: "08 17 15 6 *"
    - cron: "08 23 15 6 *"

jobs:
  collect-data-job-08-17-15-6-star-6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            github_actions/update_workflow/schedules.xlsx
            github_actions/update_workflow/update_workflow.py
            p6_deployment/collect_data.py
          sparse-checkout-cone-mode: false
          # ref: prod  # Branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Run collect_data script
        run: python p6_deployment/collect_data.py --id_country 6

      - name: Commit and push predictions.xlsx
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add p6_deployment/data/predicciones.xlsx
          git commit -m "Add updated predicciones.xlsx"
          git push
        env:
          # Set the environment variable GITHUB_TOKEN if needed for push authentication
          GITHUB_TOKEN: ${ secrets.TOKEN }
