name: Update results

on:
  schedule: # Se ejecutan en horario UTC 0 y con 15' de retraso...
    # - cron: "0 0 * * *"  # Ejecutar todos los dias a la medianoche
    - cron: "15 21 * * *"  # Se corre a las 18.15 de arg  (partidos que arrancan a las 16.30hs) 
    - cron: "45 17 * * *"  # Se corre a las 15.30 hs de ARG (partidos que arrancan a las 13.30hs)     # - cron: "15 18 * * *"  # Se corre a las 15.30 hs de ARG (partidos que arrancan a las 13.30hs)
    - cron: "45 15 * * *"  # Se corre a las 13 hs de ARG (partidos que arrancan a las 11hs) -->
    - cron: "45 14 * * *"  # Se corre a las 12 hs de ARG (partidos que arrancan a las 10hs) --> DOMINGO
    - cron: "45 13 * * *"  # Se corre a las 11 hs de ARG (partidos que arrancan a las 8.30hs) --> SABADO PREMIER
  push: # Para hacer que se ejecute la action
    branches:
      - staging

jobs:
  collect_results:
    runs-on: ubuntu-latest

    env:
      TZ: America/Argentina/Buenos_Aires

    # Agrego permisos en job para poder hacer push
    permissions: 
      contents: write  # para poder hacer git push

    steps:
      - name: Print current date and time
        run: date
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            set_up_logging.py
            data/df_countries.xlsx
            data/df_competencies.xlsx
            data/historial_predicciones.xlsx
            data/predicciones.xlsx
            p2_data_understanding/collect_initial_data
            p3_data_preparation/construct_data.py
            p3_data_preparation/clean_data.py
            p4_modeling
            p6_deployment/automatize_predict
            p6_deployment/requirements_mnm.txt
          sparse-checkout-cone-mode: false
          ref: prod # Branch

      # Instalacion de dependencias 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
 
      - name: Set up cache for pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/p6_deployment/requirements_mnm.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r p6_deployment/requirements_mnm.txt

      # Run update_results script
      - name: Run update_results script
        run: |
          python p6_deployment/automatize_predict/update_results.py 1 # Con 1 seria suficiente puesto que lo corro todos los dias. Pero pongo dos por holgura

      # Push to Github
      - name: Commit and push all changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Set the environment variable GITHUB_TOKEN if needed for push authentication
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .  # Agregar todos los cambios
          git commit -m "Update results of bets"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:prod

      # Dispath to transfer
      - name: Dispatch event to second repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python p6_deployment/automatize_predict/dispatch_event/dispatch_event.py
