name: Update results

on:
  schedule: # Se ejecutan en horario UTC 0 (arg es -3) y con 15' de retraso...

    # Todos los dias a la medianoche
    # - cron: "00 21 * * *" # 18.00 hs
    - cron: "00 22 * * *" # 19.00 hs (x seguridad)

    # Viernes
    # - cron: "0 19 * * 5" # 16hs ARG
    - cron: "00 21 * * 5" # 18:00hs ARG
    # - cron: "45 21 * * 5" # 18:45hs ARG

    # Sabado
    - cron: "30 13 * * 6" # 10:30 hs ARG
    - cron: "30 15 * * 6" # 12:30 hs ARG
    # - cron: "0 16 * * 6" # 13:00 hs ARG
    - cron: "30 16 * * 6" # 13:30 hs ARG
    - cron: "0 17 * * 6" #  14:00 hs ARG
    # - cron: "30 18 * * 6" # 15:30 hs ARG
    - cron: "45 19 * * 6" #  16:45 hs ARG
    - cron: "00 21 * * 6" # 18:00 hs ARG
    # - cron: "45 21 * * 6" # 18:45 hs ARG

    # Domingo
    - cron: "30 13 * * 0" # 10:30 hs ARG
    - cron: "00 16 * * 0" # 13:00 hs ARG
    # - cron: "0 17 * * 0" #  14:00 hs ARG
    - cron: "0 18 * * 0"  # 15:00 hs ARG
    - cron: "15 19 * * 0"  # 16:15 hs ARG
    - cron: "00 21 * * 0" # 18:00 hs ARG
    # - cron: "45 21 * * 0" # 18:45 hs ARG
  
    # Lunes
    # - cron: "30 18 * * 1" # 15:30 hs ARG
    - cron: "00 21 * * 1" # 18:00 hs ARG
    # - cron: "45 21 * * 1" # 18:45 hs ARG

  # Para forzar a que se ejecute la action  
  push: 
    branches:
      - staging

jobs:
  collect_results:
    runs-on: ubuntu-latest

    env:
      TZ: America/Argentina/Buenos_Aires
      ENVIRONMENT: "prod"

    # Agrego permisos en job para poder hacer push
    permissions: 
      contents: write  # para poder hacer git push

    steps:
      - name: Print current date and time
        run: date

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            utils
            data/df_countries.xlsx
            data/df_competencies.xlsx
            data/historial_predicciones.xlsx
            data/predicciones.xlsx
            p2_data_understanding/collect_initial_data
            p3_data_preparation/format_data.py
            p3_data_preparation/construct_data.py
            p3_data_preparation/clean_data.py
            p4_modeling
            p6_deployment
          sparse-checkout-cone-mode: false
          ref: prod # Branch # Prueba con staging

      # Instalacion de dependencias 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
 
      - name: Set up cache for pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/p6_deployment/requirements_mnm.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r p6_deployment/requirements_mnm.txt

      # - name: Set n_days based on hour
      #   id: set-ndays
      #   run: |
      #     current_hour=$(date +"%H")  # Hora actual solo HH. Se compara la hora (HH), ignorando los minutos, lo que hace que sea menos sensible a posibles retrasos.
      #     echo "La hora actual es: $current_hour"
      #     if [ "$current_hour" == "10" ]; then
      #       echo "n_days=0.2" >> $GITHUB_ENV            
      #     elif [ "$current_hour" == "12" ]; then
      #       echo "n_days=0.2" >> $GITHUB_ENV
      #     elif [ "$current_hour" == "13" ]; then
      #       echo "n_days=0.5" >> $GITHUB_ENV
      #     elif [ "$current_hour" == "14" ]; then
      #       echo "n_days=0.2" >> $GITHUB_ENV
      #     elif [ "$current_hour" == "15" ]; then
      #       echo "n_days=0.2" >> $GITHUB_ENV
      #     elif [ "$current_hour" == "16" ]; then
      #       echo "n_days=0.2" >> $GITHUB_ENV
      #     elif [ "$current_hour" == "18" ]; then
      #       echo "n_days=0.20" >> $GITHUB_ENV
      #     else
      #       echo "n_days=1.00" >> $GITHUB_ENV  # Valor predeterminado en caso de error
      #     fi  # ¡Cerrar el bloque condicional correctamente!

      # Run update_results script
      - name: Run update_results script
        run: |
          python p6_deployment/automatize_predict/update_results.py 1
          # echo "Ejecutando el script con n_days=${{ env.n_days }}"
          # python p6_deployment/automatize_predict/update_results.py ${{ env.n_days }}

      # Push to Github
      - name: Commit and push all changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Set the environment variable GITHUB_TOKEN if needed for push authentication
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .  # Agregar todos los cambios
          git commit -m "Update results of bets"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:prod

      # Dispath to transfer
      - name: Dispatch event to second repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python p6_deployment/automatize_predict/dispatch_event/dispatch_event.py
